---
# file: tasks/validation.yml
#
# validation tasks.
#

- fail:
    msg="only Ubuntu is supported"
  when: ansible_distribution != 'Ubuntu'

- fail:
    msg="only Ubuntu >= 12.04 is supported"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('12.04', '<')

- name: ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - awscli_configuration
    - awscli_profiles
    - awscli_users
    - awscli_version
